---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# todo update to aap after PR to gitops-catalog
namespace: ansible-automation-platform

resources:
  - serviceaccount.yaml
  - secret.yaml

