---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/hub-instance/overlays/?ref=main
  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/instance/overlays/default?ref=main
  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/hub-instance/overlays/default?ref=main


# error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
#patches:

patchesStrategicMerge:
  - patch-automationcontroller.yaml
  - patch-automationhub.yaml
  - patch-consolelink.yaml
